### ISSUE TITLE
It doesn't seem to be working anymore.

### ISSUE THREAD

**Issue by crobertsbmw** [multichess/multichess.github.io#1]
All I see is a bunch of template code that looks like it was sumped to the main page. Too bad. This was a fun concept.

**Comment by theborakompanioni** [comment]
@crobertsbmw someone actually looked into it, nice. I am sorry I have not taken care of the service - it was backed by a single instance on a tiny server long forgotten. It seems I won't have time dealing with it in the near future. :|

However, feel free to browse the code or run your own version. That'd be cool.

**Comment by theborakompanioni** [comment]
@crobertsbmw Found the instance. Restarted. Thank you!
